# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 385d8afaf19b979162eb436b80e628732622f4038dffd3ae5b749363b168f2a55620f84cbb28dbf82d71705dd1e38e422fb0e64c382d6ddca40f2fc0eb128691

test:
  secret_key_base: 0b19ad25ebdb5b5764fee29b2331bd2608b610e66b52d501fc6ca817947bbdba6a840c8071811492784decf2c2217a7d8d29bf6d8f5c0ec84b525bfc26d7e664

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
